/**
 * Supabase Service & Data Access Layer
 * 
 * Instructions to set up Supabase table in Supabase Dashboard -> SQL Editor:
 * 
 * -- Enable pgcrypto extension for gen_random_uuid()
 * CREATE EXTENSION IF NOT EXISTS "pgcrypto";
 * 
 * CREATE TABLE tshirt_registrations (
 *   id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
 *   registration_no INT GENERATED BY DEFAULT AS IDENTITY,
 *   created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
 *   name TEXT NOT NULL,
 *   mobile TEXT NOT NULL,
 *   size TEXT NOT NULL,
 *   status TEXT DEFAULT 'Pending' NOT NULL
 * );
 * 
 * -- Enable Row Level Security (RLS)
 * ALTER TABLE tshirt_registrations ENABLE ROW LEVEL SECURITY;
 * 
 * -- Public Access Policies
 * CREATE POLICY "Allow anonymous read access" ON tshirt_registrations FOR SELECT USING (true);
 * CREATE POLICY "Allow anonymous insert access" ON tshirt_registrations FOR INSERT WITH CHECK (true);
 * CREATE POLICY "Allow anonymous update access" ON tshirt_registrations FOR UPDATE USING (true);
 * CREATE POLICY "Allow anonymous delete access" ON tshirt_registrations FOR DELETE USING (true);
 */

import { createClient } from '@supabase/supabase-js';
import { JANMASTHAMI_CONFIG } from '../data/data';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn("Supabase credentials missing! Please configure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env");
}

export const supabase = (supabaseUrl && supabaseAnonKey)
  ? createClient(supabaseUrl, supabaseAnonKey)
  : null;

/**
 * Fetch all t-shirt registrations ordered by creation date
 */
export const fetchRegistrations = async () => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .select('*')
    .order('created_at', { ascending: true });

  if (error) throw error;
  return { data, source: 'supabase' };
};

/**
 * Submit a new T-shirt registration directly to Supabase DB
 */
export const submitRegistration = async ({ name, mobile, size }) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const newEntry = {
    name: name.trim(),
    mobile: mobile.trim(),
    size,
    status: 'Pending'
  };

  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .insert([newEntry])
    .select();

  if (error) throw error;
  return { success: true, data: data[0], source: 'supabase' };
};

/**
 * Update registration status in Supabase DB
 */
export const updateRegistrationStatus = async (id, status) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .update({ status })
    .eq('id', id)
    .select();

  if (error) throw error;
  return { success: true, data };
};

/**
 * Delete a registration from Supabase DB
 */
export const deleteRegistration = async (id) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const { error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .delete()
    .eq('id', id);

  if (error) throw error;
  return { success: true };
};

/**
 * Fix and re-sequence registration numbers sequentially (1, 2, 3...)
 * ordered by creation date directly in Supabase DB
 */
export const fixRegistrationNumbering = async () => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  // Fetch all entries ordered by creation date ascending
  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .select('*')
    .order('created_at', { ascending: true });

  if (error) throw error;

  if (data && data.length > 0) {
    // Update each item with new sequential number
    for (let i = 0; i < data.length; i++) {
      const newNo = i + 1;
      const { error: updateErr } = await supabase
        .from(JANMASTHAMI_CONFIG.supabaseTableName)
        .update({ registration_no: newNo })
        .eq('id', data[i].id);
      
      if (updateErr) throw updateErr;
    }
  }

  return { success: true, count: data ? data.length : 0 };
};
