/**
 * Supabase Service & Data Access Layer
 * 
 * Instructions to set up Supabase table in Supabase Dashboard -> SQL Editor:
 * 
 * -- Enable pgcrypto extension for gen_random_uuid()
 * CREATE EXTENSION IF NOT EXISTS "pgcrypto";
 * 
 * CREATE TABLE tshirt_registrations (
 *   id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
 *   registration_no INT GENERATED BY DEFAULT AS IDENTITY,
 *   created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
 *   name TEXT NOT NULL,
 *   mobile TEXT NOT NULL,
 *   size TEXT NOT NULL,
 *   status TEXT DEFAULT 'Pending' NOT NULL
 * );
 * 
 * -- Enable Row Level Security (RLS)
 * ALTER TABLE tshirt_registrations ENABLE ROW LEVEL SECURITY;
 * 
 * -- Public Access Policies
 * CREATE POLICY "Allow anonymous read access" ON tshirt_registrations FOR SELECT USING (true);
 * CREATE POLICY "Allow anonymous insert access" ON tshirt_registrations FOR INSERT WITH CHECK (true);
 * CREATE POLICY "Allow anonymous update access" ON tshirt_registrations FOR UPDATE USING (true);
 * CREATE POLICY "Allow anonymous delete access" ON tshirt_registrations FOR DELETE USING (true);
 */

import { createClient } from '@supabase/supabase-js';
import { JANMASTHAMI_CONFIG } from '../data/data';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn("Supabase credentials missing! Please configure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env");
}

export const supabase = (supabaseUrl && supabaseAnonKey)
  ? createClient(supabaseUrl, supabaseAnonKey)
  : null;

/**
 * Fetch all t-shirt registrations ordered by creation date
 */
export const fetchRegistrations = async () => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .select('*')
    .order('created_at', { ascending: true });

  if (error) throw error;
  return { data, source: 'supabase' };
};

/**
 * Submit a new T-shirt registration directly to Supabase DB
 */
export const submitRegistration = async ({ name, mobile, size, payment_screenshot_url }) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const newEntry = {
    name: name.trim(),
    mobile: mobile.trim(),
    size,
    payment_screenshot_url: payment_screenshot_url || '',
    status: 'Pending'
  };

  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .insert([newEntry])
    .select();

  if (error) throw error;
  return { success: true, data: data[0], source: 'supabase' };
};

/**
 * Fetch dynamic T-shirt settings (price, QR code URL, sample image URL, description)
 */
export const fetchTShirtSettings = async () => {
  if (!supabase) {
    return { data: null, error: "Supabase client not initialized" };
  }

  try {
    const { data, error } = await supabase
      .from(JANMASTHAMI_CONFIG.supabaseSettingsTableName || 'tshirt_settings')
      .select('*')
      .eq('id', 1)
      .maybeSingle();

    if (error) {
      console.warn("Could not fetch tshirt_settings from Supabase:", error.message);
      return { data: null, error: error.message };
    }

    return { data, error: null };
  } catch (err) {
    console.warn("Failed to fetch tshirt_settings:", err.message);
    return { data: null, error: err.message };
  }
};

/**
 * Update dynamic T-shirt settings (price, QR code URL, sample image URL, description)
 */
export const updateTShirtSettings = async ({ price, qr_code_url, sample_image_url, description }) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const payload = {
    price: Number(price) || 250,
    qr_code_url: qr_code_url || '',
    sample_image_url: sample_image_url || '',
    description: description || '',
    updated_at: new Date().toISOString()
  };

  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseSettingsTableName || 'tshirt_settings')
    .upsert({ id: 1, ...payload })
    .select();

  if (error) throw error;
  return { success: true, data: data[0] };
};

/**
 * Update registration status in Supabase DB
 */
export const updateRegistrationStatus = async (id, status) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .update({ status })
    .eq('id', id)
    .select();

  if (error) throw error;
  return { success: true, data };
};

/**
 * Update full registration details (Name, Mobile, Size, Status, Screenshot URL)
 */
export const updateRegistrationDetails = async (id, { name, mobile, size, status, payment_screenshot_url }) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const payload = {
    name: name.trim(),
    mobile: mobile.trim(),
    size,
    status: status || 'Pending',
    payment_screenshot_url: payment_screenshot_url || ''
  };

  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .update(payload)
    .eq('id', id)
    .select();

  if (error) throw error;
  return { success: true, data: data[0] };
};

/**
 * Admin direct registration entry (No payment screenshot or QR code required)
 */
export const adminCreateRegistration = async ({ name, mobile, size, status, payment_screenshot_url }) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const newEntry = {
    name: name.trim(),
    mobile: mobile.trim(),
    size,
    status: status || 'Accepted',
    payment_screenshot_url: payment_screenshot_url || ''
  };

  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .insert([newEntry])
    .select();

  if (error) throw error;
  return { success: true, data: data[0] };
};

/**
 * Delete a registration from Supabase DB
 */
export const deleteRegistration = async (id) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const { error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .delete()
    .eq('id', id);

  if (error) throw error;
  return { success: true };
};

/**
 * Fix and re-sequence registration numbers sequentially (1, 2, 3...)
 * ordered by creation date directly in Supabase DB
 */
export const fixRegistrationNumbering = async () => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  // Fetch all entries ordered by creation date ascending
  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseTableName)
    .select('*')
    .order('created_at', { ascending: true });

  if (error) throw error;

  if (data && data.length > 0) {
    // Update each item with new sequential number
    for (let i = 0; i < data.length; i++) {
      const newNo = i + 1;
      const { error: updateErr } = await supabase
        .from(JANMASTHAMI_CONFIG.supabaseTableName)
        .update({ registration_no: newNo })
        .eq('id', data[i].id);
      
      if (updateErr) throw updateErr;
    }
  }

  return { success: true, count: data ? data.length : 0 };
};

/**
 * Fetch all Instagram Reels from Supabase
 */
export const fetchInstagramReels = async () => {
  if (!supabase) {
    return { data: [], source: 'local' };
  }

  try {
    const { data, error } = await supabase
      .from(JANMASTHAMI_CONFIG.supabaseReelsTableName || 'instagram_reels')
      .select('*')
      .order('display_order', { ascending: true })
      .order('created_at', { ascending: false });

    if (error) {
      console.warn("Could not fetch instagram_reels:", error.message);
      return { data: [], error: error.message };
    }

    return { data: data || [], source: 'supabase' };
  } catch (err) {
    console.warn("Failed to fetch instagram_reels:", err.message);
    return { data: [], error: err.message };
  }
};

/**
 * Add a new Instagram Reel to Supabase
 */
export const addInstagramReel = async ({ title, reel_url, category, display_order }) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const newEntry = {
    title: title.trim(),
    reel_url: reel_url.trim(),
    category: category ? category.trim() : 'Janmashtami Highlights',
    display_order: display_order ? parseInt(display_order) : 1
  };

  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseReelsTableName || 'instagram_reels')
    .insert([newEntry])
    .select();

  if (error) throw error;
  return { success: true, data: data[0] };
};

/**
 * Update an existing Instagram Reel in Supabase
 */
export const updateInstagramReel = async (id, { title, reel_url, category, display_order }) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const updatedData = {
    title: title.trim(),
    reel_url: reel_url.trim(),
    category: category ? category.trim() : 'Janmashtami Highlights',
    display_order: display_order ? parseInt(display_order) : 1
  };

  const { data, error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseReelsTableName || 'instagram_reels')
    .update(updatedData)
    .eq('id', id)
    .select();

  if (error) throw error;
  return { success: true, data: data[0] };
};

/**
 * Delete an Instagram Reel from Supabase
 */
export const deleteInstagramReel = async (id) => {
  if (!supabase) {
    throw new Error("Supabase client is not initialized. Please check your .env file.");
  }

  const { error } = await supabase
    .from(JANMASTHAMI_CONFIG.supabaseReelsTableName || 'instagram_reels')
    .delete()
    .eq('id', id);

  if (error) throw error;
  return { success: true };
};
